services:
  - type: web 
    name: nest-users-api
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: |
      bash -e '
      until pg_isready -k "$DB_HOST" -p "$DB_PORT" -U "$DB_USER" -d "$DB_NAME"; do
        echo "Waiting for database..."
        sleep 2
      done
      npm run build
      npm run migration:run
      npm run seed:run
      node dist/src/main.js
      '
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: '3000'
      - key: DB_HOST
        fromDatabase:
          name: nest-users-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: nest-users-db
          property: port
      - key: DB_USER
        fromDatabase:
          name: nest-users-db
          property: user
      - key: DB_PASS
        fromDatabase:
          name: nest-users-db
          property: password
      - key: DB_NAME
        fromDatabase:
          name: nest-users-db
          property: database
databases:
  - name: nest-users-db
    plan: free
